version: "3"

tasks:
  build:
    desc: build project
    cmds: [go build -o build/server/idp-server cmd/server/main.go]
  test:
    desc: test project
    cmds: [go test ./...]
    deps: [setup-local-db]
  setup-local-db:
    desc: run docker-compose
    cmds: [docker-compose -f docker/docker-compose.yml up -d]
